
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: true
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "A"
        versions: ["2.0.0"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: true
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "B"
        versions: ["1.0.1"]
