version: 2
updates:
  # Configuration for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "axios"
        versions: ["< 1.6.0"]

  # Configuration for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "some-python-package"
        versions: ["< 2.0.0"]
