trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover
  displayName: 'Run tests'

- script: |
    zip -r release.zip .
  displayName: 'Package application'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure Service Connection>'  # Replace with your Azure service connection name
    appName: '<App Service Name>'  # Replace with your Azure App Service name
    package: $(System.DefaultWorkingDirectory)/release.zip
