version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "axios"
        versions: ["< 1.6.0"]
