trigger:
  branches:
    include:
      - PlaidBridgeOpenBankingApi

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Name for the container image repository.
  imageName: 'plaidbridgeopenbankingapi'
  # Commit ID will be used as the tag (built-in variable).
  commitId: $(Build.SourceVersion)
  # OpenShift registry URL
  containerRegistry: $(OPENSHIFT_REGISTRY)
  # OpenShift project name
  openshiftProject: 'YourOpenShiftProject'  # Replace with your actual OpenShift project name

stages:
- stage: Build
  displayName: 'Build and Push Podman Image'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      # Use Podman to build and push the image to OpenShift registry.
      - script: |
          podman build -t $(imageName):$(commitId) .
          podman tag $(imageName):$(commitId) $(containerRegistry)/$(imageName):$(commitId)
          podman push $(containerRegistry)/$(imageName):$(commitId)
        displayName: 'Build and Push Podman Image'

- stage: Deploy
  displayName: 'Deploy to OpenShift'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
      # Log in to OpenShift
      - script: |
          oc login --server=$(OPENSHIFT_SERVER) --token=$(OPENSHIFT_TOKEN)
        displayName: 'OpenShift Login'

      # Deploy the container to OpenShift
      - script: |
          oc apply -f openshift-deployment.yml
          oc rollout restart deployment/$(imageName)
        displayName: 'Deploy to OpenShift'
