"""Add timeline_events table

Revision ID: 4bbd87e8395e
Revises: bc6b0eacef38
Create Date: 2026-01-10 22:40:10.087790

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4bbd87e8395e"
down_revision = "bc6b0eacef38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timeline_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_timeline_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    op.alter_column(
        "todos",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column("todos", "text", existing_type=mysql.VARCHAR(length=255), nullable=False)
    op.alter_column(
        "todos",
        "completed",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "todos",
        "priority",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column("todos", "created_at", existing_type=mysql.DATETIME(), nullable=False)
    op.alter_column(
        "todos",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(op.f("ix_todos_user_id"), "todos", ["user_id"], unique=False)
    op.alter_column(
        "user_dashboards",
        "user_id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "user_dashboards",
        "settings",
        existing_type=mysql.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column("user_dashboards", "created_at", existing_type=mysql.DATETIME(), nullable=False)
    op.alter_column("user_dashboards", "updated_at", existing_type=mysql.DATETIME(), nullable=False)
    op.alter_column(
        "users",
        "id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_approved",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_mfa_enabled",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_users_uuid"), table_name="users")
    op.create_unique_constraint(op.f("uq_users_uuid"), "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_uuid"), "users", type_="unique")
    op.create_index(op.f("idx_users_uuid"), "users", ["uuid"], unique=True)
    op.alter_column(
        "users",
        "is_mfa_enabled",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_approved",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column("user_dashboards", "updated_at", existing_type=mysql.DATETIME(), nullable=True)
    op.alter_column("user_dashboards", "created_at", existing_type=mysql.DATETIME(), nullable=True)
    op.alter_column(
        "user_dashboards",
        "settings",
        existing_type=sa.JSON(),
        type_=mysql.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_dashboards",
        "user_id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_todos_user_id"), table_name="todos")
    op.alter_column(
        "todos",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column("todos", "created_at", existing_type=mysql.DATETIME(), nullable=True)
    op.alter_column(
        "todos",
        "priority",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'normal'"),
        existing_nullable=False,
    )
    op.alter_column(
        "todos",
        "completed",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column("todos", "text", existing_type=mysql.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "todos",
        "user_id",
        existing_type=sa.String(length=36),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.drop_table("timeline_events")
    # ### end Alembic commands ###
   
