"""empty message

Revision ID: 71105643d932
Revises: 51c060321aba
Create Date: 2026-02-15 04:17:29.025966

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '71105643d932'
down_revision = '51c060321aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trace_events_user_id_users'), 'trace_events', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_trace_events_user_id_users'),
        'trace_events',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trace_events_user_id_users'), 'trace_events', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_trace_events_user_id_users'),
        'trace_events',
        'users',
        ['user_id'],
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###