"""fix revoked_tokens FK + seed admin user

Revision ID: 9e5cc67d40a0
Revises:
Create Date: 2025-11-02 17:31:15.794804
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text as sa_text

# revision identifiers, used by Alembic.
revision = "9e5cc67d40a0"
down_revision = None
branch_labels = None
depends_on = None

# --- CONSTANTS ---
ADMIN_EMAIL = "admin@example.com"
ADMIN_HASH = (
    "scrypt:32768:8:1$drZ6JiSwfe3E3Xzg$dc3a8c64ddabbf169a1b0b1a1011655ebb31"
    "a58560de827f61c639cfc3dee0d49e44d7500736792946ad1c85e3c708f5ddfa4376bc"
    "746b0ee1d19125ee93c872"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limits")),
        sa.UniqueConstraint("ip_address", name=op.f("uq_rate_limits_ip_address")),
    )
    op.create_table(
        "system_boot_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("sequence_origin", sa.String(length=255), nullable=True),
        sa.Column("ignition_timestamp", sa.DateTime(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_boot_logs")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("has_mfa", sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "mfa_pending_setup",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_mfa_enabled"), "users", ["mfa_enabled"], unique=False)
    op.create_index(
        op.f("ix_users_mfa_pending_setup"), "users", ["mfa_pending_setup"], unique=False
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    # ... all your other op.create_table() calls for access_tokens, bank_accounts, etc.
    # (unchanged from the Alembic‑autogenerated baseline you already had)

    # --- Seed initial admin user with literal hash ---
    conn = op.get_bind()
    conn.execute(
        sa_text(
            "INSERT INTO users (username, email, password_hash, role, is_admin, "
            "has_mfa, mfa_enabled, mfa_pending_setup, created_at) "
            "VALUES (:username, :email, :password_hash, :role, :is_admin, 0, 0, 0, NOW())"
        ),
        {
            "username": "admin",
            "email": ADMIN_EMAIL,
            "password_hash": ADMIN_HASH,
            "role": "admin",
            "is_admin": True,
        },
    )


def downgrade():
    # --- Remove seeded admin user before dropping tables ---
    conn = op.get_bind()
    conn.execute(sa_text("DELETE FROM users WHERE email = :email"), {"email": ADMIN_EMAIL})

    # Drop in reverse order of creation
    op.drop_table("subscriptions")
    op.drop_table("ledger_entries")
    op.drop_table("fraud_reports")
    op.drop_table("complaint_logs")
    op.drop_table("bank_transactions")
    op.drop_table("vault_transactions")
    op.drop_table("user_dashboards")
    op.drop_table("underwriter_agents")
    op.drop_table("transactions")
    op.drop_table("tradelines")
    op.drop_table("trace_events")
    op.drop_table("system_versions")
    op.drop_table("subscriber_profile")
    op.drop_table("schema_event")
    op.drop_index(op.f("ix_revoked_tokens_jti"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_table("registries")
    op.drop_table("plaid_items")
    op.drop_table("payment_log")
    op.drop_index(op.f("ix_mfa_codes_code"), table_name="mfa_codes")
    op.drop_table("mfa_codes")
    op.drop_table("loan_agreement")
    op.drop_table("lenders")
    op.drop_table("dispute_log")
    op.drop_table("credit_ledger")
    op.drop_table("borrower_cards")
    op.drop_table("bank_statements")
    op.drop_table("bank_institutions")
    op.drop_index("ix_user_id", table_name="bank_accounts")
    op.drop_index("ix_account_number", table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_table("access_tokens")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_mfa_pending_setup"), table_name="users")
    op.drop_index(op.f("ix_users_mfa_enabled"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("system_boot_logs")
    op.drop_table("rate_limits")
