# =============================================================================
# FILE: app/services/pdf_generator.py
# DESCRIPTION: Cockpit-grade PDF generation with Markdown support.
# =============================================================================

import os
from datetime import datetime
from typing import Any

# -----------------------------------------------------------------------------
# Optional Markdown import with typed fallback
# -----------------------------------------------------------------------------
try:
    from markdown import Markdown  # type: ignore[import-untyped]
except Exception:

    class Markdown:  # type: ignore[no-redef]
        """
        Typed fallback stub for environments without the 'markdown' package.
        Provides a .convert() method returning plain text.
        """

        def __init__(self, *args: Any, **kwargs: Any) -> None:
            pass

        def convert(self, text: str) -> str:
            return text


# -----------------------------------------------------------------------------
# PDF generation dependencies
# -----------------------------------------------------------------------------
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

from app.cockpit.tracers.ttl_pulse import log_pdf_export_pulse

EXPORT_DIR = "/plaidbridge/exports/pdf"


# =============================================================================
# Minimal Markdown → Text helper (required by tests)
# =============================================================================
def _minimal_markdown_to_text(markdown: str) -> str:
    """
    Extremely small markdown-to-text helper used by tests.
    Strips headings, bold/italic markers, and code fences.
    Not a full markdown parser — intentionally minimal.
    """
    if not markdown:
        return ""

    text = markdown

    # Remove code fences
    text = text.replace("```", "")

    # Remove bold/italic markers
    for token in ("**", "__", "*", "_"):
        text = text.replace(token, "")

    # Strip leading '#' from headings
    lines = []
    for line in text.splitlines():
        stripped = line.lstrip("# ").rstrip()
        lines.append(stripped)

    return "\n".join(lines).strip()


# =============================================================================
# Core PDF helpers
# =============================================================================
def ensure_export_dir():
    """Ensures the directory for PDF exports exists."""
    if not os.path.exists(EXPORT_DIR):
        os.makedirs(EXPORT_DIR)


def generate_filename(prefix="audit", ext="pdf"):
    """Generates a unique filename based on a prefix and timestamp."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H%M%SZ")
    return f"{prefix}_{timestamp}.{ext}"


def build_pdf(
    content_lines: list[str],
    title="Cockpit Export",
    operator="system",
    filename=None,
):
    """
    Builds a PDF document from a list of strings, with basic formatting.
    """
    ensure_export_dir()
    filename = filename or generate_filename()
    filepath = os.path.join(EXPORT_DIR, filename)

    c = canvas.Canvas(filepath, pagesize=LETTER)
    width, height = LETTER

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 50, title)
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 65, f"Generated by: {operator}")
    c.drawString(50, height - 80, f"UTC Timestamp: {datetime.utcnow().isoformat()}")

    # Body
    y = height - 120
    for line in content_lines:
        if y < 50:
            c.showPage()
            y = height - 50
        c.drawString(50, y, line)
        y -= 15

    c.save()

    # TTL pulse log
    log_pdf_export_pulse(filename=filename, operator=operator)

    return {
        "filename": filename,
        "filepath": filepath,
        "timestamp": datetime.utcnow().isoformat(),
        "operator": operator,
    }


# =============================================================================
# Public API expected by tests
# =============================================================================
def generate_pdf_from_markdown(
    markdown_text: str,
    title: str = "Markdown Export",
    operator: str = "system",
):
    """
    Converts markdown to plain text (minimal) and generates a PDF.
    """
    text = _minimal_markdown_to_text(markdown_text)
    lines = [line for line in text.split("\n") if line.strip()]
    return build_pdf(lines, title=title, operator=operator)


def generate_pdf_from_html(
    html_text: str,
    title: str = "HTML Export",
    operator: str = "system",
):
    """
    Extremely minimal HTML → text converter for test compatibility.
    Strips tags and collapses whitespace.
    """
    import re

    # Remove HTML tags
    text = re.sub(r"<[^>]+>", "", html_text)
    lines = [line.strip() for line in text.split("\n") if line.strip()]
    return build_pdf(lines, title=title, operator=operator)


def render_pdf_from_markdown(markdown_content: str, title: str, operator: str) -> dict:
    """
    Legacy wrapper used by older parts of the app.
    """
    content_lines = markdown_content.split("\n")
    content_lines = [line.strip() for line in content_lines if line.strip()]
    return build_pdf(content_lines, title=title, operator=operator)
