"""dry run schema diff

Revision ID: 11b5ce097bf4
Revises: f996868ab1a4
Create Date: 2025-11-15 17:55:26.064559

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "11b5ce097bf4"
down_revision = "f996868ab1a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_access_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_access_tokens_token")),
    )
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_type", sa.String(length=32), nullable=True),
        sa.Column("account_number", sa.String(length=64), nullable=False),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("trace_status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bank_accounts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_accounts")),
        sa.UniqueConstraint("account_number", name=op.f("uq_bank_accounts_account_number")),
    )
    op.create_index("ix_account_number", "bank_accounts", ["account_number"], unique=False)
    op.create_index("ix_user_id", "bank_accounts", ["user_id"], unique=False)
    op.create_table(
        "bank_institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("institution_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bank_institutions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_institutions")),
        sa.UniqueConstraint("institution_id", name=op.f("uq_bank_institutions_institution_id")),
    )
    op.create_table(
        "bank_statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bank", sa.String(length=100), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("txn_count", sa.Integer(), nullable=True),
        sa.Column("source_api", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bank_statements_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_statements")),
    )
    op.create_table(
        "borrower_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_number", sa.String(length=16), nullable=False),
        sa.Column("expiration_date", sa.String(length=5), nullable=False),
        sa.Column("cvv", sa.String(length=3), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=10), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("trace_status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_borrower_cards_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrower_cards")),
        sa.UniqueConstraint("card_number", name=op.f("uq_borrower_cards_card_number")),
    )
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.String(length=64), nullable=False),
        sa.Column("credit_limit", sa.Float(), nullable=True),
        sa.Column("balance_used", sa.Float(), nullable=True),
        sa.Column("last_payment_ts", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("suspended", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_credit_ledger_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_ledger")),
    )
    op.create_table(
        "dispute_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("template_title", sa.String(length=128), nullable=False),
        sa.Column("bureau", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("email_status", sa.String(length=16), nullable=True),
        sa.Column("sendgrid_id", sa.String(length=128), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("delivery_ts", sa.DateTime(), nullable=True),
        sa.Column("acknowledged_ts", sa.DateTime(), nullable=True),
        sa.Column("response_notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dispute_log_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispute_log")),
    )
    op.create_table(
        "lenders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("business_name", sa.String(length=100), nullable=False),
        sa.Column("owner_name", sa.String(length=100), nullable=False),
        sa.Column("ssn_or_ein", sa.String(length=20), nullable=False),
        sa.Column("license_number", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=150), nullable=False),
        sa.Column("institution_name", sa.String(length=100), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=True),
        sa.Column("verification_score", sa.Integer(), nullable=True),
        sa.Column("bank_linked", sa.Boolean(), nullable=True),
        sa.Column("linked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_lenders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lenders")),
    )
    op.create_table(
        "loan_agreement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lender_id", sa.Integer(), nullable=False),
        sa.Column("borrower_id", sa.Integer(), nullable=False),
        sa.Column("terms", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("ai_flagged", sa.Boolean(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=True),
        sa.Column("violation_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["users.id"],
            name=op.f("fk_loan_agreement_borrower_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["lender_id"], ["users.id"], name=op.f("fk_loan_agreement_lender_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_agreement")),
    )
    op.create_table(
        "mfa_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("fail_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_mfa_codes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mfa_codes")),
    )
    op.create_index(op.f("ix_mfa_codes_code"), "mfa_codes", ["code"], unique=False)
    op.create_table(
        "payment_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("payment_processor_id", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_payment_log_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_log")),
    )
    op.create_table(
        "plaid_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plaid_item_id", sa.String(length=128), nullable=False),
        sa.Column("access_token", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_plaid_items_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plaid_items")),
    )
    op.create_table(
        "registries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("config_blob", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_registries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registries")),
        sa.UniqueConstraint("name", name=op.f("uq_registries_name")),
    )
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_revoked_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revoked_tokens")),
    )
    op.create_index(op.f("ix_revoked_tokens_jti"), "revoked_tokens", ["jti"], unique=True)
    op.create_table(
        "schema_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("origin", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_schema_event_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_event")),
    )
    op.create_table(
        "subscriber_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("bank_name", sa.String(length=100), nullable=False),
        sa.Column("routing_number", sa.String(length=20), nullable=False),
        sa.Column("account_last4", sa.String(length=4), nullable=True),
        sa.Column("ssn_last4", sa.String(length=4), nullable=True),
        sa.Column("ein", sa.String(length=10), nullable=True),
        sa.Column("business_name", sa.String(length=120), nullable=True),
        sa.Column("business_address", sa.String(length=255), nullable=True),
        sa.Column("business_city", sa.String(length=120), nullable=True),
        sa.Column("home_address", sa.String(length=255), nullable=False),
        sa.Column("same_address_flag", sa.Boolean(), nullable=True),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("api_key", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_subscriber_profile_user"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriber_profile")),
        sa.UniqueConstraint("api_key", name=op.f("uq_subscriber_profile_api_key")),
        sa.UniqueConstraint("email", name=op.f("uq_subscriber_profile_email")),
        sa.UniqueConstraint("username", name=op.f("uq_subscriber_profile_username")),
    )
    op.create_table(
        "system_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_hash", sa.String(length=40), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_system_versions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_versions")),
    )
    op.create_table(
        "trace_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("meta", sa.Text(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trace_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_trace_events_event_id")),
    )
    op.create_table(
        "tradelines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vendor_name", sa.String(length=100), nullable=False),
        sa.Column("tradeline_type", sa.String(length=50), nullable=True),
        sa.Column("credit_limit", sa.Integer(), nullable=True),
        sa.Column("annual_fee", sa.Float(), nullable=True),
        sa.Column("reports_to", sa.String(length=255), nullable=True),
        sa.Column("terms_url", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_tradelines_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tradelines")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plaid_account_id", sa.String(length=120), nullable=True),
        sa.Column("account_id", sa.String(length=120), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("is_pending", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_transactions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_table(
        "underwriter_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("specialty", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_underwriter_agents_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_underwriter_agents")),
    )
    op.create_table(
        "user_dashboards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("settings", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_dashboards_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_dashboards")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_dashboards_user_id")),
    )
    op.create_table(
        "vault_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_vault_transactions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault_transactions")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_vault_transactions_transaction_id")),
    )
    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_account_id", sa.Integer(), nullable=True),
        sa.Column("to_account_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("txn_type", sa.String(length=32), nullable=True),
        sa.Column("method", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_bank_transactions_from_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_bank_transactions_to_account_id_bank_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_transactions")),
    )
    op.create_table(
        "complaint_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_complaint_logs_transaction_id_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_complaint_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint_logs")),
    )
    op.create_table(
        "fraud_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_fraud_reports_transaction_id_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_fraud_reports_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fraud_reports")),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("borrower_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("reconciled", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["borrower_id"],
            ["users.id"],
            name=op.f("fk_ledger_entries_borrower_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["borrower_cards.id"],
            name=op.f("fk_ledger_entries_card_id_borrower_cards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("subscriber_profile_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscriber_profile_id"],
            ["subscriber_profile.id"],
            name="fk_subscriptions_subscriber_profile",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.add_column("users", sa.Column("ssn_last4", sa.String(length=4), nullable=True))
    op.add_column("users", sa.Column("primary_phone", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("bank_name", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("routing_number", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("account_ending", sa.String(length=8), nullable=True))
    op.add_column("users", sa.Column("business_address", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("ein", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("business_city", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("business_state", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("business_zip", sa.String(length=16), nullable=True))
    op.add_column("users", sa.Column("business_phone", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("home_address", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("home_same_as_business", sa.Boolean(), nullable=True))
    op.alter_column(
        "users",
        "has_mfa",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "mfa_enabled",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "mfa_pending_setup",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "mfa_pending_setup",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "mfa_enabled",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "has_mfa",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.drop_column("users", "home_same_as_business")
    op.drop_column("users", "home_address")
    op.drop_column("users", "business_phone")
    op.drop_column("users", "business_zip")
    op.drop_column("users", "business_state")
    op.drop_column("users", "business_city")
    op.drop_column("users", "ein")
    op.drop_column("users", "business_address")
    op.drop_column("users", "account_ending")
    op.drop_column("users", "routing_number")
    op.drop_column("users", "bank_name")
    op.drop_column("users", "primary_phone")
    op.drop_column("users", "ssn_last4")
    op.drop_table("subscriptions")
    op.drop_table("ledger_entries")
    op.drop_table("fraud_reports")
    op.drop_table("complaint_logs")
    op.drop_table("bank_transactions")
    op.drop_table("vault_transactions")
    op.drop_table("user_dashboards")
    op.drop_table("underwriter_agents")
    op.drop_table("transactions")
    op.drop_table("tradelines")
    op.drop_table("trace_events")
    op.drop_table("system_versions")
    op.drop_table("subscriber_profile")
    op.drop_table("schema_event")
    op.drop_index(op.f("ix_revoked_tokens_jti"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_table("registries")
    op.drop_table("plaid_items")
    op.drop_table("payment_log")
    op.drop_index(op.f("ix_mfa_codes_code"), table_name="mfa_codes")
    op.drop_table("mfa_codes")
    op.drop_table("loan_agreement")
    op.drop_table("lenders")
    op.drop_table("dispute_log")
    op.drop_table("credit_ledger")
    op.drop_table("borrower_cards")
    op.drop_table("bank_statements")
    op.drop_table("bank_institutions")
    op.drop_index("ix_user_id", table_name="bank_accounts")
    op.drop_index("ix_account_number", table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_table("access_tokens")
    # ### end Alembic commands ###
