"""Add totp_secret column to User

Revision ID: 211bf581ad99
Revises: 4c3ceeaf8283
Create Date: 2025-11-17 16:45:54.618812

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "211bf581ad99"
down_revision = "4c3ceeaf8283"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_secret", sa.String(length=64), nullable=True))
    op.alter_column("users", "username", existing_type=mysql.VARCHAR(length=64), nullable=False)
    op.alter_column("users", "role", existing_type=mysql.VARCHAR(length=64), nullable=False)
    op.alter_column(
        "users",
        "is_admin",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column("users", "created_at", existing_type=mysql.DATETIME(), nullable=False)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_totp_secret"), "users", ["totp_secret"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_totp_secret"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column("users", "created_at", existing_type=mysql.DATETIME(), nullable=True)
    op.alter_column(
        "users", "is_admin", existing_type=mysql.TINYINT(display_width=1), nullable=True
    )
    op.alter_column("users", "role", existing_type=mysql.VARCHAR(length=64), nullable=True)
    op.alter_column("users", "username", existing_type=mysql.VARCHAR(length=64), nullable=True)
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
