"""verify_schema_sync

Revision ID: 88acc6dec986
Revises: 1c9be1c52e4b
Create Date: 2026-07-29 22:32:52.689842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88acc6dec986'
down_revision = '1c9be1c52e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
