"""Add extended profile fields to users

Revision ID: f996868ab1a4
Revises: 9e5cc67d40a0
Create Date: 2025-11-12 15:15:29.122569

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f996868ab1a4"
down_revision = "9e5cc67d40a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("ssn_last4", sa.String(length=4), nullable=True))
    op.add_column("users", sa.Column("primary_phone", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("bank_name", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("routing_number", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("account_ending", sa.String(length=8), nullable=True))
    op.add_column("users", sa.Column("business_address", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("ein", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("business_city", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("business_state", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("business_zip", sa.String(length=16), nullable=True))
    op.add_column("users", sa.Column("business_phone", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("home_address", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("home_same_as_business", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "home_same_as_business")
    op.drop_column("users", "home_address")
    op.drop_column("users", "business_phone")
    op.drop_column("users", "business_zip")
    op.drop_column("users", "business_state")
    op.drop_column("users", "business_city")
    op.drop_column("users", "ein")
    op.drop_column("users", "business_address")
    op.drop_column("users", "account_ending")
    op.drop_column("users", "routing_number")
    op.drop_column("users", "bank_name")
    op.drop_column("users", "primary_phone")
    op.drop_column("users", "ssn_last4")
    # ### end Alembic commands ###
