# pdf_writers.py

import os
from datetime import datetime

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

# Optional: TTL pulse tracer
from app.cockpit.tracers.ttl_pulse import log_pdf_export_pulse

EXPORT_DIR = "/plaidbridge/exports/pdf"


def ensure_export_dir():
    if not os.path.exists(EXPORT_DIR):
        os.makedirs(EXPORT_DIR)


def narratable_filename(prefix="audit", ext="pdf"):
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H%M%SZ")
    return f"{prefix}_{timestamp}.{ext}"


def write_pdf(content_lines, filename=None, title="Cockpit Export", operator="system"):
    ensure_export_dir()
    filename = filename or narratable_filename()
    filepath = os.path.join(EXPORT_DIR, filename)

    c = canvas.Canvas(filepath, pagesize=LETTER)
    width, height = LETTER

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 50, title)
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 65, f"Generated by: {operator}")
    c.drawString(50, height - 80, f"UTC Timestamp: {datetime.utcnow().isoformat()}")

    # Content
    y = height - 120
    for line in content_lines:
        if y < 50:
            c.showPage()
            y = height - 50
        c.drawString(50, y, line)
        y -= 15

    c.save()

    # TTL pulse log
    log_pdf_export_pulse(filename=filename, operator=operator)

    return filepath
