# =============================================================================
# FILE: app/models/mfa_code.py
# DESCRIPTION: Robust MFACode model with helper constructors, validators,
#              consumption semantics, TTL helpers, failure counters, and
#              maintenance utilities. Designed for clear operator intent,
#              explicit commits, and minimal surprises in concurrent flows.
# =============================================================================

from __future__ import annotations

import logging
from datetime import datetime, timedelta

from sqlalchemy.exc import SQLAlchemyError

from app.extensions import db

logger = logging.getLogger(__name__)


class MFACode(db.Model):
    """
    MFA Code model

    Responsibilities:
    - Persist a single active one-time MFA code per user (create_or_replace helper).
    - Track creation/expiry timestamps and failure counts.
    - Provide helpers for validation, consumption, TTL inspection, and cleanup.
    - Minimise race conditions by deleting existing rows before creating a new one
      within the same DB transaction.
    """

    __tablename__ = "mfa_codes"

    # -------------------------------------------------------------------------
    # Columns
    # -------------------------------------------------------------------------
    id = db.Column(db.Integer, primary_key=True)

    # ✔ Updated to match User.id (String(36))
    # ✔ Added ondelete="CASCADE"
    user_id = db.Column(
        db.String(36),
        db.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    code = db.Column(db.String(32), nullable=False, index=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    expires_at = db.Column(db.DateTime, nullable=False, index=True)
    fail_count = db.Column(db.Integer, default=0, nullable=False)

    # -------------------------------------------------------------------------
    # Relationships
    # -------------------------------------------------------------------------
    user = db.relationship("User", back_populates="mfa_codes", lazy="joined")

    # -------------------------------------------------------------------------
    # Construction / lifecycle helpers
    # -------------------------------------------------------------------------
    @classmethod
    def create_or_replace(
        cls, user_id: str, code: str, ttl_seconds: int = 600, commit: bool = True
    ) -> MFACode:
        """
        Atomically create a new MFACode for a user, deleting any existing one first.

        - user_id: target user (UUID string)
        - code: plaintext one-time code (already generated by caller)
        - ttl_seconds: lifetime in seconds (default 600)
        - commit: whether to commit the DB transaction here

        Returns the persisted MFACode instance.
        """
        try:
            existing = cls.query.filter_by(user_id=user_id).first()
            if existing:
                db.session.delete(existing)
                db.session.flush()

            now = datetime.utcnow()
            obj = cls(
                user_id=user_id,
                code=code,
                created_at=now,
                expires_at=now + timedelta(seconds=ttl_seconds),
                fail_count=0,
            )
            db.session.add(obj)

            if commit:
                db.session.commit()
            else:
                db.session.flush()

            return obj

        except SQLAlchemyError:
            db.session.rollback()
            logger.exception("Failed to create_or_replace MFACode for user_id=%s", user_id)
            raise

    @classmethod
    def get_active_for_user(cls, user_id: str) -> MFACode | None:
        """
        Return the (first) active MFACode for a user or None if none exists.
        Active means expires_at in the future.
        """
        now = datetime.utcnow()
        return (
            cls.query.filter_by(user_id=user_id)
            .filter(cls.expires_at > now)
            .order_by(cls.created_at.desc())
            .first()
        )

    # -------------------------------------------------------------------------
    # Instance helpers
    # -------------------------------------------------------------------------
    def is_valid(self) -> bool:
        """Return True if the code has not expired."""
        return datetime.utcnow() < self.expires_at

    def time_remaining(self) -> int:
        """Seconds remaining until expiry. Returns 0 when expired."""
        remaining = int((self.expires_at - datetime.utcnow()).total_seconds())
        return max(0, remaining)

    def increment_fail(self, commit: bool = True) -> None:
        """Increment fail_count, persist optionally."""
        try:
            self.fail_count = (self.fail_count or 0) + 1
            db.session.add(self)

            if commit:
                db.session.commit()
            else:
                db.session.flush()

        except SQLAlchemyError:
            db.session.rollback()
            logger.exception(
                "Failed to increment fail_count for MFACode id=%s",
                getattr(self, "id", None),
            )
            raise

    def consume(self, commit: bool = True) -> None:
        """
        Mark this MFACode as consumed by deleting the row.
        After consume it should no longer be considered valid.
        """
        try:
            db.session.delete(self)

            if commit:
                db.session.commit()
            else:
                db.session.flush()

        except SQLAlchemyError:
            db.session.rollback()
            logger.exception("Failed to consume MFACode id=%s", getattr(self, "id", None))
            raise

    def validate_and_consume(self, submitted_code: str, max_failures: int = 10) -> bool:
        """
        Validate a submitted code against this instance.
        - If valid and not expired: consume and return True.
        - If invalid: increment fail_count and return False.
        - If fail_count exceeds max_failures, consume to avoid brute-force persistence.
        """
        if not self.is_valid():
            try:
                db.session.delete(self)
                db.session.commit()
            except SQLAlchemyError:
                db.session.rollback()
                logger.exception(
                    "Failed to delete expired MFACode id=%s", getattr(self, "id", None)
                )
            return False

        if secrets_compare(submitted_code, self.code):
            self.consume(commit=True)
            return True

        self.increment_fail(commit=True)

        if (self.fail_count or 0) >= max_failures:
            try:
                db.session.delete(self)
                db.session.commit()
            except SQLAlchemyError:
                db.session.rollback()
                logger.exception(
                    "Failed to purge MFACode after excessive failures id=%s",
                    getattr(self, "id", None),
                )

        return False

    # -------------------------------------------------------------------------
    # Maintenance utilities
    # -------------------------------------------------------------------------
    @classmethod
    def purge_expired(cls, older_than_seconds: int | None = None) -> int:
        """
        Delete expired MFACode rows. Optionally restrict to codes expired longer than
        `older_than_seconds` to avoid deleting very recently expired codes.
        Returns number of rows deleted.
        """
        now = datetime.utcnow()
        threshold = (
            now if older_than_seconds is None else now - timedelta(seconds=older_than_seconds)
        )

        try:
            q = cls.__table__.delete().where(cls.expires_at <= threshold)
            result = db.session.execute(q)
            db.session.commit()
            return result.rowcount or 0

        except SQLAlchemyError:
            db.session.rollback()
            logger.exception("Failed to purge expired MFACode rows")
            raise

    @classmethod
    def list_for_user(cls, user_id: str) -> list[dict]:
        """Return serialisable summaries of MFACode rows for audit/troubleshooting."""
        rows = cls.query.filter_by(user_id=user_id).order_by(cls.created_at.desc()).all()
        return [
            {
                "id": r.id,
                "code": r.code,
                "created_at": r.created_at.isoformat(),
                "expires_at": r.expires_at.isoformat(),
                "time_remaining": r.time_remaining(),
                "fail_count": r.fail_count,
            }
            for r in rows
        ]

    # -------------------------------------------------------------------------
    # Representation
    # -------------------------------------------------------------------------
    def to_dict(self) -> dict:
        """
        Serialisable representation for logs or telemetry
        (avoid sending codes to external telemetry).
        """
        return {
            "id": self.id,
            "user_id": self.user_id,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "time_remaining": self.time_remaining(),
            "fail_count": self.fail_count,
        }

    def __repr__(self) -> str:
        return (
            f"<MFACode id={self.id} user_id={self.user_id} "
            f"expires_at={self.expires_at.isoformat()}>"
        )


# -------------------------------------------------------------------------
# Small utilities local to this module
# -------------------------------------------------------------------------
def secrets_compare(a: str | None, b: str | None) -> bool:
    """
    Constant-time comparison helper to reduce timing attack surface.
    Accepts None and returns False if either side is falsy.
    """
    import hmac

    if not a or not b:
        return False

    return hmac.compare_digest(str(a), str(b))
