name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - PlaidBridgeOpenBankingApi
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - PlaidBridgeOpenBankingApi

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'PlaidBridgeOpenBankingApi' # App source code path
          api_location: 'PlaidBridgeOpenBankingApi' # Api source code path
          output_location: 'build' # Built app content directory
