- task: AzureCLI@2 # Or another task using azure/login as a dependency
  inputs:
    azureSubscription: 'your-azure-subscription'
    scriptType: 'bash'
    script: |
      az account show
  # ... other steps ...

- task: AzureLogin@1 # Older version
  inputs:
    azureSubscription: 'your-azure-subscription'
    servicePrincipalId: '$(servicePrincipalId)'
    servicePrincipalKey: '$(servicePrincipalKey)'
    tenantId: '$(tenantId)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'your-azure-subscription'
    scriptType: 'pscore'
    script: |
      Get-AzSubscription
  # ... other steps ...

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'your-azure-rm-connection'
    subscriptionId: '$(subscriptionId)'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
