name: Azure Container Apps CI/CD

on:
  push:
    branches:
      - PlaidBridgeOpenBankingApi
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - PlaidBridgeOpenBankingApi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment (for build context if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Build the Docker image using the provided Dockerfile.
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/plaidbridgeopenbankingapi:${{ github.sha }} .

      # Log in to Azure Container Registry (ACR)
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Push the Docker image to ACR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/plaidbridgeopenbankingapi:${{ github.sha }}

      # Upload the image tag artifact for the deploy job (optional)
      - name: Upload image tag artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: image-tag
          path: ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the image tag artifact (optional; for reference)
      - name: Download image tag artifact
        uses: actions/download-artifact@v3.1.2
        with:
          name: image-tag

      # Deploy the container to Azure Container Apps
      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy@v1
        id: deploy
        with:
          resource-group: 'YourResourceGroup'  # Replace with your actual Resource Group name
          containerapp-name: ${{ secrets.AZURE_CONTAINERAPP_NAME }}
          acr-image: '${{ secrets.ACR_LOGIN_SERVER }}/plaidbridgeopenbankingapi:${{ github.sha }}'
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
