name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ] # Testing across Python versions

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 4: Install dependencies and tools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install waitress>=3.0.1 gunicorn>=23.0.0 requests>=2.32.0
        pip install pytest pytest-cov flake8 # Adding linting and test coverage tools

    # Step 5: Lint the codebase
    - name: Run linter
      run: flake8 .

    # Step 6: Run tests with coverage
    - name: Run tests
      run: |
        pytest --cov=your_project_dir tests/ # Replace your_project_dir with your actual project directory

    # Step 7: Upload coverage reports (optional, requires coverage tools)
    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml # Requires pytest-cov configured to output coverage.xml

