name: Build and Deploy Container to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Build Docker Image with GitHub
      - name: Build Docker Image
        run: docker build . -t newlevelplayingfield.azurecr.io/plaidbridgeopenbankingapi:latest

      # Step 4: Push Docker Image to Azure Container Registry (ACR)
      - name: Push Docker Image
        run: |
          docker login newlevelplayingfield.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push newlevelplayingfield.azurecr.io/plaidbridgeopenbankingapi:latest

      # Optional Step 5: Deploy to Azure Kubernetes Service (AKS)
      - name: Deploy to Azure Kubernetes Service
        uses: azure/k8s-deploy@v3
        with:
          manifests: ./k8s/deployment.yaml
          images: newlevelplayingfield.azurecr.io/plaidbridgeopenbankingapi:latest








