name: Build and Deploy Python App to OpenShift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (version 3.12)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the Podman Image
      - name: Build Podman image
        run: |
          podman build -t plaidbridgeopenbankingapi .

      # Step 5: Log in to OpenShift
      - name: OpenShift Login
        run: |
          oc login --server=${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }}

      # Step 6: Push Image to OpenShift Registry
      - name: Push Podman Image to OpenShift
        run: |
          podman tag plaidbridgeopenbankingapi ${{ secrets.OPENSHIFT_REGISTRY }}/plaidbridgeopenbankingapi:latest
          podman push ${{ secrets.OPENSHIFT_REGISTRY }}/plaidbridgeopenbankingapi:latest

      # Step 7: Deploy to OpenShift
      - name: Deploy to OpenShift
        run: |
          oc apply -f openshift-deployment.yml
          oc rollout restart deployment/plaidbridgeopenbankingapi
