name: Run Endpoints

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server
        run: |
          nohup python app.py &
        env:
          FLASK_ENV: development

      - name: Wait for server to start
        run: sleep 10

      - name: Test create_link_token endpoint
        run: curl -X GET http://0.0.0.0:8000/create_link_token

      - name: Test exchange_public_token endpoint
        run: curl -X POST http://0.0.0.0:8000/exchange_public_token -H "Content-Type: application/json" -d '{"public_token": "sample_token"}'

      - name: Test upload_pdf endpoint
        run: curl -X POST http://0.0.0.0:8000/upload-pdf -F 'file=@sample.pdf'
