name: Run Endpoints

on: [push, pull_request]

jobs:
  run-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask Application
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ENV: ${{ secrets.PLAID_ENV }}
        run: |
          nohup python app.py &
          sleep 20 # Increased sleep time

      - name: Wait for Flask Application to start
        run: |
          for i in {1..5}; do
            curl http://127.0.0.1:5000 && break || sleep 5
          done

      - name: Test Endpoints
        run: |
          curl -X POST http://127.0.0.1:5000/exchange-public-token -H "Content-Type: application/json" -d '{"public_token": "sample_token"}'
          curl -X POST http://127.0.0.1:5000/create-link-token
          curl -X POST http://127.0.0.1:5000/create-payment-token -H "Content-Type: application/json" -d '{"public_token": "sample_token", "recipient_id": "sample_recipient", "reference": "sample_reference", "amount": 100}'
          curl -X POST http://127.0.0.1:5000/make-payment -H "Content-Type: application/json" -d '{"public_token": "sample_token", "recipient_id": "sample_recipient", "reference": "sample_reference", "amount": 100}
