name: Run Endpoints

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask application
      run: |
        nohup python app.py &
        sleep 10

    - name: Run curl commands
      run: |
        curl -X POST http://0.0.0.0:5000/exchange-public-token -H "Content-Type: application/json" -d '{"public_token": "sample_token"}'
        curl -X POST http://0.0.0.0:5000/create-link-token
        curl -X POST http://0.0.0.0:5000/create-payment-token -H "Content-Type: application/json" -d '{"public_token": "sample_token", "recipient_id": "sample_recipient", "reference": "sample_reference", "amount": "sample_amount"}'
        curl -X POST http://0.0.0.0:5000/make-payment -H "Content-Type: application/json" -d '{"public_token": "sample_token", "recipient_id": "sample_recipient", "reference": "sample_reference", "amount": "sample_amount"}'
