name: Security Check

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.13' # Specify the Python version

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2

